default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
development:
  <<: \\*default
  database: windows_bash_test_application_development
  username: postgres
  password: <%= Rails.application.credentials[:postgress_database][:password] %>
  port: 5432
test:
  <<: \\*default
  database: windows_bash_test_application_test
  username: postgres
  password: <%= Rails.application.credentials[:postgress_database][:password] %>
production:
  <<: \\*default
  database: windows_bash_test_application_production
  username: windows_bash_test_application
  password: <%= ENV['WINDOWS_BASH_TEST_APPLICATION_DATABASE_PASSWORD'] %>